package com.isw.delivereat.ui.payment

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import android.widget.ArrayAdapter
import androidx.appcompat.app.AppCompatActivity
import com.isw.delivereat.R
import com.isw.delivereat.dto.Direccion
import kotlinx.android.synthetic.main.direccion_activity.*

/**
 * Created by Jeremias Gersicich on 2019-05-21
 */
class DireccionActivity : AppCompatActivity() {
    private lateinit var adapter: ArrayAdapter<String>
    val CIUDADES = arrayOf(
        "Ballesteros",
        "Río Bamba",
        "Río Ceballos",
        "Bialet Massé",
        "Jesús María",
        "La Cautiva",
        "La Granja",
        "La Palestina",
        "Colazo",
        "Alto Alegre",
        "Colonia Marina",
        "Adelia María",
        "Achiras",
        "Agua de Oro",
        "Alcira",
        "Almafuerte",
        "Alpa Corral",
        "Alto de los Quebrachos",
        "Amboy",
        "Ambul",
        "Anisacate",
        "Arias",
        "Arroyito",
        "Arroyo los Patos",
        "Atahona",
        "Ausonia",
        "Avellaneda",
        "Ballesteros Sud",
        "Balnearia",
        "Bañado de Soto",
        "Bell Ville",
        "Bengolea",
        "Benjamín Gould",
        "Berrotarán",
        "Bouwer",
        "Brinkmann",
        "Buchardo",
        "Cavanagh",
        "Cañada de Luque",
        "Cabalango",
        "Villa del Dique",
        "Calmayo",
        "Camilo Aldao",
        "Caminiaga",
        "Canals",
        "Candelaria Sud",
        "Capilla de los Remedios",
        "Capilla del Carmen",
        "Capilla del Sitón",
        "Capitán General B. O'Higgins",
        "Carnerillo",
        "Carrilobo",
        "Cañada de Río Pinto",
        "Cerro Colorado",
        "Chaján",
        "Casa Grande",
        "Charbonier",
        "Chañar Viejo",
        "Chilibroste",
        "Chuña",
        "Charras",
        "Chuña Huasi",
        "Ciénaga del Coro",
        "Colonia Bremen",
        "Colonia Caroya",
        "Colonia las Cuatro Esquinas",
        "Colonia Prosperidad",
        "Colonia Italiana",
        "Colonia Iturraspe",
        "Colonia Tirolesa",
        "Comechingones",
        "Colonia las Pichanas",
        "Villa Yacanto",
        "Conlara",
        "Copacabana",
        "Coronel Moldes",
        "Corralito",
        "El Rastreador",
        "Costasacate",
        "Cruz de Caña",
        "Embalse",
        "Colonia San Bartolomé",
        "Cuesta Blanca",
        "Del Campillo",
        "Despeñaderos",
        "Devoto",
        "Diego de Rojas",
        "Dique Chico",
        "El Chacho",
        "El Crispín",
        "El Fortín",
        "Guatimozín",
        "El Manzano",
        "El Rodeo",
        "Esquina",
        "Estación General Paz",
        "Estación Juárez Celman",
        "Estancia de Guadalupe",
        "Estancia Vieja",
        "Etruria",
        "Eufrasio Loza",
        "Falda del Carmen",
        "General Cabrera",
        "Guanaco Muerto",
        "Guasapampa",
        "Hernando",
        "Huerta Grande",
        "Huinca Renancó",
        "Idiazabal",
        "Impira",
        "Isla Verde",
        "James Craik",
        "La Calera",
        "La Cesira",
        "La Francia",
        "La Cruz",
        "La Cumbre",
        "La Paquita",
        "La Cumbrecita",
        "La Falda",
        "La Higuera",
        "La Laguna",
        "Laborde",
        "Laboulaye",
        "Laguna Larga",
        "Colonia San Pedro",
        "La Paisanita",
        "La Pampa",
        "La Para",
        "La Paz",
        "La Playa",
        "La Población",
        "La Puerta",
        "La Quinta",
        "La Rancherita",
        "La Rinconada",
        "General Deheza",
        "La Serranita",
        "La Tordilla",
        "Las Acequias",
        "General Fotheringham",
        "Las Albahacas",
        "Las Arrias",
        "Las Bajadas",
        "Las Caleras",
        "Las Calles",
        "Las Cañadas",
        "Las Higueras",
        "Las Isletillas",
        "Las Junturas",
        "Las Perdices",
        "Las Peñas",
        "Las Playas",
        "Las Rabonas",
        "Las Tapias",
        "Las Varillas",
        "Leones",
        "Los Cedros",
        "General Levalle",
        "Las Vertientes",
        "Leguizamón",
        "Los Cerrillos",
        "Los Chañaritos (C.D. Eje)",
        "Los Chañaritos",
        "Los Cisnes",
        "Los Cocos",
        "Los Hornillos",
        "Los Hoyos",
        "Los Mistoles",
        "Los Pozos",
        "Maquinista Gallini",
        "Marull",
        "Los Reartes",
        "Los Talares",
        "Los Zorros",
        "Lozada",
        "Lucio V. Mansilla",
        "Luque",
        "Luyaba",
        "Malagueño",
        "Malena",
        "Pampayasta Norte",
        "Panaholma",
        "Malvinas Argentinas",
        "Manfredi",
        "Marcos Juárez",
        "Potrero de Garay",
        "Matorrales",
        "Mattaldi",
        "Mayu Sumaj",
        "Media Naranja",
        "Mendiolaza",
        "Río de los Sauces",
        "Mi Granja",
        "Monte Cristo",
        "Monte de los Gauchos",
        "Monte Leña",
        "Monte Maíz",
        "Morrison",
        "Morteros",
        "Nicolás Bruzzone",
        "Noetinger",
        "Nono",
        "Obispo Trejo",
        "Olivares de San Nicolás",
        "Onagoity",
        "Oncativo",
        "Ordóñez",
        "Pacheco de Melo",
        "Pampayasta Sud",
        "Pascanas",
        "Piquillín",
        "Pilar",
        "Plaza de Mercedes",
        "Plaza Luxardo",
        "Porteña",
        "Pozo del Molle",
        "Pozo Nuevo",
        "Pueblo Italiano",
        "Puesto de Castro",
        "Quilino",
        "Rafael García",
        "Ranqueles",
        "Rayo Cortado",
        "Reducción",
        "Río Cuarto",
        "Río Segundo",
        "Río Tercero",
        "Rosario del Saladillo",
        "Saladillo",
        "San Clemente",
        "Saira",
        "Saldán",
        "Salsacate",
        "Salsipuedes",
        "Sampacho",
        "San Agustín",
        "San Antonio de Arredondo",
        "San Antonio de Litín",
        "San Marcos Sud",
        "Santa Catalina",
        "Santa Eufemia",
        "Santiago Temple",
        "San Carlos Minas",
        "San Esteban",
        "San Francisco del Chañar",
        "San Gerónimo",
        "San Ignacio",
        "San Javier y Yacanto",
        "San Joaquín",
        "San José",
        "San José de la Dormida",
        "San José de las Salinas",
        "San Lorenzo",
        "San Marcos Sierras",
        "San Pedro",
        "San Pedro Norte",
        "San Roque",
        "San Vicente",
        "Santa María de Punilla",
        "Santa Rosa de Calamuchita",
        "Sarmiento",
        "Saturnino María Laspiur",
        "Sebastián Elcano",
        "Seeber",
        "Segunda Usina",
        "Serrano",
        "Villa Concepción del Tío",
        "Serrezuela",
        "Silvio Pellico",
        "Villa del Prado",
        "Sinsacate",
        "Suco",
        "Tala Cañada",
        "Tala Huasi",
        "Talaini",
        "Tinoco",
        "Tío Pujio",
        "Toro Pujio",
        "Toledo",
        "Tosno",
        "Villa la Bolsa",
        "Unquillo",
        "Valle Hermoso",
        "Villa Allende",
        "Villa Amancay",
        "Villa Rossi",
        "Villa Ascasubi",
        "Villa Candelaria Norte",
        "Villa San Esteban",
        "Villa Cerro Azul",
        "Villa Cura Brochero",
        "Villa de las Rosas",
        "Villa de María",
        "Villa de Pocho",
        "Villa de Soto",
        "Paso del Durazno",
        "Capilla del Monte",
        "Villa del Totoral",
        "Villa Dolores",
        "Villa Fontana",
        "Villa General Belgrano",
        "Villa Giardino",
        "Villa Huidobro",
        "Villa los Aromos",
        "Villa los Patos",
        "Cosquín",
        "Alta Gracia",
        "Colonia Videla",
        "Freyre",
        "La Posta",
        "Mina Clavero",
        "Aldea Santa María",
        "Alejandro Roca",
        "Alejo Ledesma",
        "Alicia",
        "Arroyo Cabral",
        "Altos de Chipión",
        "Ana Zumarán",
        "Assunta",
        "Bulnes",
        "Calchín",
        "Calchín Oeste",
        "Chalacea",
        "Chancaní",
        "Chazón",
        "Churqui Cañada",
        "Cañada de Machado",
        "Cañada del Sauce",
        "Chucul",
        "Cintra",
        "Colonia Almada",
        "Colonia Anita",
        "Colonia Barge",
        "Colonia Bismarck",
        "Colonia Valtelina",
        "Colonia Vicente Agüero",
        "Colonia Vignaud",
        "Cruz Alta",
        "Coronel Baigorria",
        "Corral de Bustos",
        "Cruz del Eje",
        "El Arañado",
        "Dalmacio Vélez",
        "Deán Funes",
        "El Brete",
        "El Tío",
        "Elena",
        "General Baldissera",
        "General Roca",
        "Huanchilla",
        "Gütemberg",
        "Jovita",
        "Justiniano Posse",
        "Kilómetro 658",
        "La Batea",
        "Inriville",
        "Italó",
        "La Carlota",
        "La Carolina",
        "El Potosi",
        "Villa Parque Siquiman",
        "Córdoba",
        "La Playosa",
        "Las Peñas Sud",
        "Las Saladas",
        "Las Gramillas",
        "Las Palmas",
        "Las Varas",
        "Los Molinos",
        "Los Surgentes",
        "Lutti",
        "Luca",
        "Melo",
        "Monte Ralo",
        "Miramar",
        "Monte Buey",
        "Pincen",
        "Olaeta",
        "Oliva",
        "Punta del Agua",
        "Pasco",
        "Paso Viejo",
        "Quebracho Herrado",
        "Río Primero",
        "Rosales",
        "Rincón",
        "Sacanta",
        "Sagrada Familia",
        "San Basilio",
        "San Francisco",
        "Santa Elena",
        "Sauce Arriba",
        "Simbolar",
        "Tancacha",
        "Tanti",
        "Ticino",
        "Tosquita",
        "Tránsito",
        "Tuclame",
        "Ucacha",
        "Valle de Anisacate",
        "Viamonte",
        "Vicuña Mackenna",
        "Villa Ciudad Parque los Reartes",
        "Villa Carlos Paz",
        "Villa Ciudad de América",
        "Villa del Rosario",
        "Villa el Chacay",
        "Villa Elisa",
        "Villa Gutiérrez",
        "Villa Parque Santa Ana",
        "Villa Río Icho Cruz",
        "Villa Valeria",
        "Wenceslao Escalante",
        "Villa María",
        "Villa Nueva",
        "Villa Quillinzo",
        "Villa Rumipal",
        "Villa San Isidro",
        "Villa Santa Cruz del Lago",
        "Santa Rosa de Río Primero",
        "Villa Sarmiento (S. A.)",
        "Villa Sarmiento (G.R.)",
        "Villa Tulumba",
        "Washington",
        "Los Cóndores"
    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.direccion_activity)

        adapter = ArrayAdapter(
            this,
            R.layout.dropdown_menu_popup_item,
            CIUDADES
        )

        ciudadEt.setAdapter(adapter)
        ciudadEt.threshold = 3

        guardarButton.setOnClickListener {
            if (validateInputs()) {
                val direccion = Direccion(
                    calleEt.text.toString().trim(),
                    numeroEt.text.toString().trim().toInt(),
                    ciudadEt.text.toString().trim(),
                    referenciaEt.text.toString().trim()
                )

                val intent = Intent()
                intent.putExtra("direccion", direccion)
                setResult(Activity.RESULT_OK, intent)
                finish()
            }
        }
    }

    private fun validateInputs(): Boolean {
        var valid = true

        if (calleEt.text.isNullOrEmpty()) {
            calleIl.error = "Dato obligatorio"
            valid = false
        } else {
            calleIl.error = null

        }

        if (numeroEt.text.isNullOrEmpty()) {
            numeroIl.error = "Dato obligatorio"
            valid = false
        } else {
            numeroIl.error = null
        }

        if (ciudadEt.text.isNullOrEmpty()) {
            ciudadIl.error = "Dato obligatorio"
            valid = false
        } else {
            ciudadIl.error = null
        }

        if (referenciaEt.text.isNullOrEmpty()) {
            referenciaIl.error = "Dato obligatorio"
            valid = false
        } else {
            referenciaIl.error = null
        }

        return valid
    }
}